version: '3.4'

services:
  categorydb:
    image: mongo

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: Services/Category/Category.API/Dockerfile

volumes:
  mongo_data: